/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.zjgsu.face;

public class detectJNI {

  static {
      System.loadLibrary("detect");
  }

  public final static native long new_vectori__SWIG_0();
  public final static native long new_vectori__SWIG_1(long jarg1);
  public final static native long vectori_size(long jarg1, vectori jarg1_);
  public final static native long vectori_capacity(long jarg1, vectori jarg1_);
  public final static native void vectori_reserve(long jarg1, vectori jarg1_, long jarg2);
  public final static native boolean vectori_isEmpty(long jarg1, vectori jarg1_);
  public final static native void vectori_clear(long jarg1, vectori jarg1_);
  public final static native void vectori_add(long jarg1, vectori jarg1_, int jarg2);
  public final static native int vectori_get(long jarg1, vectori jarg1_, int jarg2);
  public final static native void vectori_set(long jarg1, vectori jarg1_, int jarg2, int jarg3);
  public final static native void delete_vectori(long jarg1);
  public final static native long new_vectorf__SWIG_0();
  public final static native long new_vectorf__SWIG_1(long jarg1);
  public final static native long vectorf_size(long jarg1, vectorf jarg1_);
  public final static native long vectorf_capacity(long jarg1, vectorf jarg1_);
  public final static native void vectorf_reserve(long jarg1, vectorf jarg1_, long jarg2);
  public final static native boolean vectorf_isEmpty(long jarg1, vectorf jarg1_);
  public final static native void vectorf_clear(long jarg1, vectorf jarg1_);
  public final static native void vectorf_add(long jarg1, vectorf jarg1_, float jarg2);
  public final static native float vectorf_get(long jarg1, vectorf jarg1_, int jarg2);
  public final static native void vectorf_set(long jarg1, vectorf jarg1_, int jarg2, float jarg3);
  public final static native void delete_vectorf(long jarg1);
  public final static native long new_npddetect__SWIG_0();
  public final static native long new_npddetect__SWIG_1(int jarg1, int jarg2);
  public final static native void delete_npddetect(long jarg1);
  public final static native void npddetect_load(long jarg1, npddetect jarg1_, String jarg2);
  public final static native int npddetect_gridScan__SWIG_0(long jarg1, npddetect jarg1_, long jarg2, int jarg3, int jarg4, double jarg5, double jarg6);
  public final static native int npddetect_gridScan__SWIG_1(long jarg1, npddetect jarg1_, long jarg2, int jarg3, int jarg4, double jarg5);
  public final static native int npddetect_gridScan__SWIG_2(long jarg1, npddetect jarg1_, long jarg2, int jarg3, int jarg4);
  public final static native int npddetect_detect__SWIG_0(long jarg1, npddetect jarg1_, byte[] jarg2, int jarg3, int jarg4);
  public final static native int npddetect_detect__SWIG_1(long jarg1, npddetect jarg1_, long jarg2);
  public final static native int npddetect_detect__SWIG_2(long jarg1, npddetect jarg1_, String jarg2);
  public final static native int npddetect_prescandetect__SWIG_0(long jarg1, npddetect jarg1_, byte[] jarg2, int jarg3, int jarg4, double jarg5, double jarg6);
  public final static native int npddetect_prescandetect__SWIG_1(long jarg1, npddetect jarg1_, byte[] jarg2, int jarg3, int jarg4, double jarg5);
  public final static native int npddetect_prescandetect__SWIG_2(long jarg1, npddetect jarg1_, byte[] jarg2, int jarg3, int jarg4);
  public final static native long npddetect_getXs(long jarg1, npddetect jarg1_);
  public final static native long npddetect_getYs(long jarg1, npddetect jarg1_);
  public final static native long npddetect_getSs(long jarg1, npddetect jarg1_);
  public final static native long npddetect_getScores(long jarg1, npddetect jarg1_);
  public final static native void npddetect_draw__SWIG_0(long jarg1, npddetect jarg1_, String jarg2);
  public final static native void npddetect_draw__SWIG_1(long jarg1, npddetect jarg1_, byte[] jarg2, int jarg3, int jarg4, String jarg5);
}
